# This file was generated by GoReleaser. DO NOT EDIT.
cask "ansible-static-lint" do
  version "0.7.0"

  on_macos do
    on_arm do
      sha256 "c2b5ccb9c91019a14b025d2dfe5d12455603422558f6622afaa171670f13477a"
      url "https://github.com/arhuman/ansible-static-lint/releases/download/v#{version}/ansible-static-lint_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8dbff48db0396a2314706c87567aaebb18db987a45af3d63465e6a85a7caad77"
      url "https://github.com/arhuman/ansible-static-lint/releases/download/v#{version}/ansible-static-lint_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1f1fbf6e600cdf04c0d7f607866a32437d5a8becaec3f51289e62637d11e721a"
      url "https://github.com/arhuman/ansible-static-lint/releases/download/v#{version}/ansible-static-lint_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c3365c2afca13a5f58b0eeebd6113173a3db032c746cb94ea2ca266d69db95d3"
      url "https://github.com/arhuman/ansible-static-lint/releases/download/v#{version}/ansible-static-lint_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ansible-static-lint"
  desc "Fast static linter for Ansible playbooks and roles, no Python required"
  homepage "https://github.com/arhuman/ansible-static-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "astl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/astl"]
    end
  end

  # No zap stanza required
end
